@isTest
public with sharing class ClasseDemonstraEstruturaTest {

    @isTest
    private static void metodoEstruturaControle1Test() {

        ClasseDemonstraEstrutura.metodoEstruturaControle1(1);
        ClasseDemonstraEstrutura.metodoEstruturaControle1(10);
        ClasseDemonstraEstrutura.metodoEstruturaControle1(10);
        ClasseDemonstraEstrutura.metodoEstruturaControle1(19);
        ClasseDemonstraEstrutura.metodoEstruturaControle1(50);
    }
}
